### PR TITLE
Bump deps and minimum required python version

### PR DESCRIPTION
**Pull request by dmerejkowsky**

### CODE REVIEW

**Comment by dmerejkowsky** [comment]
This also fixes the dependabot alert : https://github.com/your-tools/python-cli-ui/security/dependabot/2

**Comment by gdubicki** [comment]
Is there a good reason to drop 3.7 support? Its EOL is June 2023, over 6 months from now.

I’ve seen a trend to drop 3.7 support already in other projects and it personally makes me a bit angry because it’s user-hostile in my opinion.

I would prefer python-cli-ui to not be such project.

**Comment by dmerejkowsky** [comment]
> Is there a good reason to drop 3.7 support? Its EOL is June 2023, over 6 months from now.

My mistake - I thought 3.7 was already EOL.

Will redo the patch if I have time

**Comment by dmerejkowsky** [comment]
Now I think we can merge this

**Pull request merged**
